### ISSUE TITLE
Getting error at SSH during install - 18.04 ova fresh and 18.04 fresh ubuntu install 

### ISSUE THREAD

**Issue by hartescout** [REMnux/remnux-cli#20] opened 2020-12-20 04:18 UTC
Here is the message during `sudo remnux update`

```
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:562:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.
```
-----------------------------------------------------------

**Comment by digitalsleuth** [comment] 2020-12-20 04:22
Hi @hartescout , any chance you can attach your saltstack.log file? Either that, or the results from `grep -i -B5 "result: false"` from said log? This will help us in finding the cause of the error. 
Thanks!

**Comment by hartescout** [comment] 2020-12-20 19:22
Hello. So, I just tried again after deleting the original saltstack.log and it went through no problems. I will try my bare metal install and another VM I have as well and see if the problem continues to persist.

**Comment by digitalsleuth** [comment] 2020-12-20 19:43
Sounds good. I've tried a fresh install as well while waiting for the log file and had no issues. It likely could have been an intermittent network connection issue which prevented a salt state from completing. For the future, if you can attach the saltstack.log to the issue you raise, we'll be able to pinpoint the problem and provide a solution much easier. 

Let us know how your next install goes so we can close this issue is all goes well.

**Comment by ppil** [comment] 2020-12-22 06:29
Experiencing the same issue, repeatedly. Tried with no cache, tried waiting and trying again in case of upstream connectivity issues. Looks to be an issue installing malwoverview, but that package seems to be installed on the system, config file is copied to ~/.malwapi.conf, and simlink created under /usr/local/bin. Those three apparently failing requisites seem to be met. I'm not sure what's failing here.
[saltstack.log](https://github.com/REMnux/remnux-cli/files/5728161/saltstack.log)

**Comment by lennyzeltser** [comment] 2020-12-22 13:34
Hi, @ppil. Could you please confirm that you're running the "remnux" command directly as your non-root user? I've seen issues like what you're reporting if you run the command as the root user.

**Comment by ppil** [comment] 2020-12-22 18:07
Hey Lenny! I thought root fixed all *nix problems :stuck_out_tongue: 
I was definitely sudo-ing the install command, per [documentation](https://docs.remnux.org/install-distro/install-from-scratch). I'll give it an unprivileged shot and see if that does the trick.

**Comment by digitalsleuth** [comment] 2020-12-22 18:15
Hi @ppil, I believe the issue is due to some recent changes to pip, and the method by which is queries for versions and upgrades. I am currently working on testing possible resolutions to this issue, and will keep this issue updated.

**Comment by ppil** [comment] 2020-12-22 19:10
Well, that was bit of a pain to fix. Unprivileged install still failed, same reasons logged. Tried chowning malwoverview's files and dirs, no luck. pip/pip3 had no record of malwoverview globally, so had to activate the virtualenv to uninstall it, blow away /opt/malwoverview, then re-run the install script. That finally worked, so I assume it was an issue with the venv itself. Probably easier for most to just blow away their VM than troubleshoot this :disappointed: 

Anyway, hope this gets sorted out for other folks that can't import the OVA (_cough_ ESXi _cough_). Excited to check out v7!

**Comment by lennyzeltser** [comment] 2020-12-24 00:32
Thanks, @ppil for reporting the problem. @digitalsleuth created a temporary fix to get around the newly introduced PIP and SaltStack issue, per https://github.com/REMnux/salt-states/pull/160

**Closed as completed by lennyzeltser** 2020-12-24 00:32 UTC
