### ISSUE TITLE
REMnux errors out when i try to install

### ISSUE THREAD

**Issue by LightJester** [REMnux/remnux-cli#123] opened 2023-03-26 15:21 UTC
i am running Ubuntu the 20.04.6 iso from your website, when i try to install i get this error:
$ sudo remnux install
> remnux-cli@1.3.4.2.g87c65ef
> remnux-version: notinstalled

> downloading v2023.11.1
>> downloading remnux-salt-states-v2023.11.1.tar.gz.asc
>> downloading remnux-salt-states-v2023.11.1.tar.gz.sha256
>> downloading remnux-salt-states-v2023.11.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2023.11.1.tar.gz
> validating file remnux-salt-states-v2023.11.1.tar.gz
> validating signature for remnux-salt-states-v2023.11.1.tar.gz.sha256
> extracting update remnux-salt-states-v2023.11.1.tar.gz
> no previous REMnux version found; performing a new 'dedicated' installation.
> upgrading/updating to v2023.11.1
>> Log file: /var/cache/remnux/cli/v2023.11.1/saltstack.log

Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

please help
[saltstack.log](https://github.com/REMnux/remnux-cli/files/11072053/saltstack.log)

**Comment by digitalsleuth** [comment] 2023-03-26 15:41
Hi @LightJester , this error can be fixed by running the following, then trying the install again:

`sudo python3 -m pip install "importlib-metadata<5.0.0"`

Let us know how it goes!

**Comment by g0mxxm** [comment] 2023-03-28 01:58
Hi I meet the similar problem， and I have tried the cmd "sudo python3 -m pip install "importlib-metadata<5.0.0"", but the error still exist. 
Below are the details of the error：
![微信截图_20230328095648](https://user-images.githubusercontent.com/97378033/228106968-3d73967f-36dc-4b85-ab63-e7d6af4fe8f0.png)
Please Help.

**Comment by lennyzeltser** [comment] 2023-03-28 22:31
@g0mxxm, the error about the hash mismatch indicates that there might be a network error that prevented you from downloading the file properly.

**Comment by g0mxxm** [comment] 2023-03-29 02:20
@lennyzeltser Thank you very much, I will check my network to try to reslove this error.

**Comment by digitalsleuth** [comment] 2023-04-11 00:25
Hi @g0mxxm , have you managed to resolve this?

**Comment by copeland3300** [comment] 2023-04-27 21:26
Editing my comment...I'm also running into this issue, and while I thought I had it solved, it looks like it's still happening. It does seem to be some network issue triggered during install, as I can't reach anything after this error pops, and ultimately have to reset my network connection.

```
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/remnux/cli in the
subdirectory that matches the REMnux version you're installing.
Search for the log file for "result: false" messages and look at
the surrounding lines to diagnose the issue.

For assistance go to https://github.com/REMnux/remnux-cli/issues
```

**Comment by digitalsleuth** [comment] 2023-04-28 01:14
Hi @copeland3300 , can you upload your saltstack.log file so we can identify the issue? FWIW, the process you went through earlier (importlib-metadata ...) was the correct resolution to the problem you were having at the time. Since the install went all the way through this time (albeit with errors), your previous issue was corrected.

Once we get a chance to review your log file we'll be able to help identify the newer issue.

Cheers!

**Comment by copeland3300** [comment] 2023-04-28 02:39
As requested!

[saltstack.log](https://github.com/REMnux/remnux-cli/files/11349335/saltstack.log)

**Comment by g0mxxm** [comment] 2023-04-29 04:29
> 
Sorry for not responding immediately. When I restore the snapshot to its original state and use the VPN, most of the apps can be updated successfully, but I get an error after updating for a while. I thought it was caused by my unstable network, so I didn't pay attention to this issue anymore. I'll check again when I get home.

**Comment by g0mxxm** [comment] 2023-04-29 04:31
> 

Bro，we have the same problem.

**Closed as not planned** 2023-05-02 14:49 UTC
